### ISSUE TITLE
TypeError e._g is not a function

### ISSUE THREAD

**Issue by ddsky** [mariomka/vue-datetime#24]
After installing and registering globally I'm using it like so in a component:

`<datetime v-model="selectedDayString" monday-first></datetime>`

and `selectedDayString` being '2017-12-02'

I get

```
[Vue warn]: Error in render function: "TypeError: e._g is not a function"

found in ---> <Datetime>...
```
Any idea what I'm doing wrong here?

**Comment by kent13n** [comment]
I had exactly the same error that I fixed by updating VueJS

**Comment by aljke** [comment]
I have the same error even after updating Vue packages

**Comment by dilipnakum** [comment]
I have the same error.
i have updating Vue and vue-select packages but still getting the same error.
