### ISSUE TITLE
DatePicker calculating wrong date

### ISSUE THREAD

**Issue by T0miii** [mariomka/vue-datetime#47]
I set this date in the datepicker:

testdate: '2017-12-30T00:00:00.000+01:00',

`<datetime v-model="testdate" type="date" value-zone="Europe/Vienna" auto></datetime>`

But for some reason i cant explain i get this in the input: 29.Dez.2018

if i change the type to "date time"  i get this in the input: 30.Dez.2018, 00:00

Can some one explain this?

**Comment by jasonlfunk** [comment]
I've run into this as well. The problem is with the difference in timezones. If you set both `zone` and `value-zone` to `local`, I believe the problem goes away.

`zone='local' value-zone='local'`

**Comment by Shulkin** [comment]
I also ran into this problem. Unfortunately, using `local` `value-zone` and `zone` did not help me.

`<datetime type="date" v-model="dateModel" value-zone="local" zone="local"></datetime>`

Initially, `dateModel` = `2018-05-10T11:35:08+10:00`

But, after I pass it to datetime it becomes `2018-05-10T00:00:00.000Z`
It seems, timezone was cut off.

Interestingly, if I change datetime component type to `datetime`, the problem goes away

`<datetime type="datetime" v-model="dateModel" value-zone="local" zone="local"></datetime>`

`dateModel` = `2018-05-10T11:41:19+10:00`
After passing to datetime, `2018-05-10T11:41:19.000+10:00`
Everything is correct.

But I need only date input)

Otherwise, an excellent component!

**Comment by mariomka** [comment]
This should be resolved thanks to #61.

**Comment by parthmp** [comment]
It is not resolved, still having same **issue** as i'm writing at this time.

**Comment by rickymaciel** [comment]
Same problem

**Comment by mariomka** [comment]
@parthmp Please, can you provide reproduction?
